export const EVENT_GET = 'get'
export const EVENT_SET = 'set'
export const EVENT_PUSH = 'push'
export const EVENT_POP = 'pop'
export const EVENT_REMOVE = 'remove'
export const EVENT_SHIFT = 'shift'
export const EVENT_UNSHIFT = 'unshift'
export const EVENT_DROP = 'drop'
