export const HOOK_BEFORE_PAINT = 'hook.beforePaint'
export const HOOK_AFTER_PAINT = 'hook.afterPaint'
export const HOOK_BEFORE_REPAINT = 'hook.beforeRepaint'
export const HOOK_AFTER_REPAINT = 'hook.afterRepaint'
export const HOOK_BEFORE_INITIAL_DIGEST = 'hook.beforeInitialDigest'
export const HOOK_AFTER_INITIAL_DIGEST = 'hook.afterInitialDigest'
export const HOOK_BEFORE_UPDATE_DIGEST = 'hook.beforeUpdateDigest'
export const HOOK_AFTER_UPDATE_DIGEST = 'hook.afterUpdateDigest'
export const SESSION_PAINT = 'session.paint'
export const SESSION_REPAINT = 'session.repaint'

export const PROD = 'prod'
export const DEBUG = 'debug'
